import PokerProtocolLean.Reconstruct.ReconstructProof
import PokerProtocolLean.PKOwnership.PKOwnershipProof

/-!
# Axiom audit for the reconstruction deliverable

The commands below report the trusted Lean axioms used by the principal
reconstruction results. No protocol-specific axiom is introduced.
-/

#print axioms PokerProtocolLean.Reconstruct.ResidualCarrierProvenance.authenticated_prior_hand_yields_residual_carrier
#print axioms PokerProtocolLean.Reconstruct.ResidualCarrierProvenance.honest_rerandomizer_translation_bijective
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.relation_complete
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.valid_relation_complete
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.residual_carrier_equations_of_authenticated_lineage
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.accepted_contribution_is_zero_or_negative_card
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.corrected_slot_semantics
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.cross_key_negation_complete
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.cross_key_negation_binds_plaintexts
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.aggregatePlaintext_unique_removal
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.JointSigma.relation_iff_cross_key
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.JointSigma.sigma_complete
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.JointSigma.sigma_speciallySound
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.JointSigma.sigma_perfect_hvzk
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.SlotOr.honest_accepts
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.SlotOr.specially_sound
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.SlotOr.perfect_hvzk_algebraic
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Security.completeness_under_components
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Security.knowledge_soundness_under_components
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Security.zero_knowledge_under_components
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Security.verified_package_semantics
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Veto.no_removable_witness_without_owner_carrier
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Veto.unauthorized_slot_keeps_card
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Veto.veto_free_extraction
#print axioms PokerProtocolLean.Reconstruct.Reconstruction.Veto.veto_error_bound_negligible
#print axioms PokerProtocolLean.PKOwnership.sigma_complete
#print axioms PokerProtocolLean.PKOwnership.sigma_speciallySound
#print axioms PokerProtocolLean.PKOwnership.sigma_perfect_hvzk
